#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cairo
Version  : 1.14.6
Release  : 19
URL      : http://www.cairographics.org/releases/cairo-1.14.6.tar.xz
Source0  : http://www.cairographics.org/releases/cairo-1.14.6.tar.xz
Summary  : Multi-platform 2D graphics library
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 MIT MPL-1.1
Requires: cairo-bin
Requires: cairo-lib
Requires: cairo-doc
BuildRequires : binutils-dev
BuildRequires : docbook-xml
BuildRequires : grep
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libXrender-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : tiff-dev

%description
Cairo - Multi-platform 2D graphics library
http://cairographics.org
What is cairo
=============
Cairo is a 2D graphics library with support for multiple output
devices. Currently supported output targets include the X Window
System (via both Xlib and XCB), quartz, win32, and image buffers,
as well as PDF, PostScript, and SVG file output. Experimental backends
include OpenGL, BeOS, OS/2, and DirectFB.

%package bin
Summary: bin components for the cairo package.
Group: Binaries

%description bin
bin components for the cairo package.


%package dev
Summary: dev components for the cairo package.
Group: Development
Requires: cairo-lib
Requires: cairo-bin
Provides: cairo-devel

%description dev
dev components for the cairo package.


%package doc
Summary: doc components for the cairo package.
Group: Documentation

%description doc
doc components for the cairo package.


%package lib
Summary: lib components for the cairo package.
Group: Libraries

%description lib
lib components for the cairo package.


%prep
%setup -q -n cairo-1.14.6

%build
%configure --disable-static --disable-gtk-doc --enable-gl=no --enable-xlib=yes --enable-xcb=yes --enable-ft=yes --enable-fc=yes
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cairo-trace

%files dev
%defattr(-,root,root,-)
/usr/include/cairo/cairo-deprecated.h
/usr/include/cairo/cairo-features.h
/usr/include/cairo/cairo-ft.h
/usr/include/cairo/cairo-gobject.h
/usr/include/cairo/cairo-pdf.h
/usr/include/cairo/cairo-ps.h
/usr/include/cairo/cairo-script-interpreter.h
/usr/include/cairo/cairo-script.h
/usr/include/cairo/cairo-svg.h
/usr/include/cairo/cairo-version.h
/usr/include/cairo/cairo-xcb.h
/usr/include/cairo/cairo-xlib-xrender.h
/usr/include/cairo/cairo-xlib.h
/usr/include/cairo/cairo.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/cairo/bindings-errors.html
/usr/share/gtk-doc/html/cairo/bindings-fonts.html
/usr/share/gtk-doc/html/cairo/bindings-memory.html
/usr/share/gtk-doc/html/cairo/bindings-overloading.html
/usr/share/gtk-doc/html/cairo/bindings-path.html
/usr/share/gtk-doc/html/cairo/bindings-patterns.html
/usr/share/gtk-doc/html/cairo/bindings-return-values.html
/usr/share/gtk-doc/html/cairo/bindings-streams.html
/usr/share/gtk-doc/html/cairo/bindings-surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Error-handling.html
/usr/share/gtk-doc/html/cairo/cairo-FreeType-Fonts.html
/usr/share/gtk-doc/html/cairo/cairo-Image-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-PDF-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-PNG-Support.html
/usr/share/gtk-doc/html/cairo/cairo-Paths.html
/usr/share/gtk-doc/html/cairo/cairo-PostScript-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Quartz-(CGFont)-Fonts.html
/usr/share/gtk-doc/html/cairo/cairo-Quartz-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Raster-Sources.html
/usr/share/gtk-doc/html/cairo/cairo-Recording-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Regions.html
/usr/share/gtk-doc/html/cairo/cairo-SVG-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Script-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-Transformations.html
/usr/share/gtk-doc/html/cairo/cairo-Types.html
/usr/share/gtk-doc/html/cairo/cairo-User-Fonts.html
/usr/share/gtk-doc/html/cairo/cairo-Version-Information.html
/usr/share/gtk-doc/html/cairo/cairo-Win32-Fonts.html
/usr/share/gtk-doc/html/cairo/cairo-Win32-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-XCB-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-XLib-Surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-XLib-XRender-Backend.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-device-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-font-face-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-font-options-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-matrix-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-pattern-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-scaled-font-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-surface-t.html
/usr/share/gtk-doc/html/cairo/cairo-cairo-t.html
/usr/share/gtk-doc/html/cairo/cairo-drawing.html
/usr/share/gtk-doc/html/cairo/cairo-fonts.html
/usr/share/gtk-doc/html/cairo/cairo-support.html
/usr/share/gtk-doc/html/cairo/cairo-surfaces.html
/usr/share/gtk-doc/html/cairo/cairo-text.html
/usr/share/gtk-doc/html/cairo/cairo.devhelp2
/usr/share/gtk-doc/html/cairo/home.png
/usr/share/gtk-doc/html/cairo/index-1.10.html
/usr/share/gtk-doc/html/cairo/index-1.12.html
/usr/share/gtk-doc/html/cairo/index-1.14.html
/usr/share/gtk-doc/html/cairo/index-1.2.html
/usr/share/gtk-doc/html/cairo/index-1.4.html
/usr/share/gtk-doc/html/cairo/index-1.6.html
/usr/share/gtk-doc/html/cairo/index-1.8.html
/usr/share/gtk-doc/html/cairo/index-all.html
/usr/share/gtk-doc/html/cairo/index.html
/usr/share/gtk-doc/html/cairo/index.sgml
/usr/share/gtk-doc/html/cairo/language-bindings.html
/usr/share/gtk-doc/html/cairo/left-insensitive.png
/usr/share/gtk-doc/html/cairo/left.png
/usr/share/gtk-doc/html/cairo/right-insensitive.png
/usr/share/gtk-doc/html/cairo/right.png
/usr/share/gtk-doc/html/cairo/style.css
/usr/share/gtk-doc/html/cairo/up-insensitive.png
/usr/share/gtk-doc/html/cairo/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
/usr/lib64/cairo/libcairo-trace.so
/usr/lib64/cairo/libcairo-trace.so.0
/usr/lib64/cairo/libcairo-trace.so.0.0.0
